// Urdu translations for ZordPath
registerLanguage('ur', 'اردو', '\u{1F1F5}\u{1F1F0}', {
    pushStart: 'نیا کھیل', continue: 'جاری رکھیں', correct: '!صحیح', incorrect: '!غلط',
    tryAgain: 'دوبارہ کوشش کریں', next: 'اگلا', back: 'واپس', viewDiagram: 'خاکہ دیکھیں',
    startQuiz: '!کوئز شروع کریں', fight: 'لڑو', zord: 'زورڈ', item: 'چیز', run: 'بھاگو',
    attack: 'حملہ', switchZord: 'زورڈ بدلو', retreat: 'پیچھے ہٹو', potion: 'دوائی',
    deploy: 'تعینات', catch: 'پکڑو', block: 'روکو', action: 'عمل', talk: 'بات',
    inventory: 'سامان', map: 'نقشہ', help: 'مدد', quiz: 'کوئز',
    leaveStore: 'دکان چھوڑو', buy: 'خریدو', soldOut: 'ختم', rubies: 'یاقوت',
    healAll: 'سب زورڈز کو شفا دو', free: 'مفت', confirm: 'تصدیق', cancel: 'منسوخ',
    close: 'بند', save: 'محفوظ', delete: 'حذف', emptySlot: 'خالی جگہ',
    enterHouse: 'گھر میں جاؤ', enterStore: 'دکان میں جاؤ', enterArena: 'میدان میں جاؤ',
    readSign: 'تختی پڑھو', fishHere: 'یہاں مچھلی پکڑو', enter: 'داخل ہو', search: 'تلاش',
    exit: 'باہر نکلو', zordHospital: 'زورڈ ہسپتال', zordSpa: 'زورڈ سپا',
    testing: 'ٹیسٹنگ', levelUp: '!سطح بڑھ گئی', reportCard: 'رپورٹ کارڈ',
    strengths: 'طاقتیں', needsPractice: 'مشق کی ضرورت',
    mostMissed: 'سب سے زیادہ غلط سوالات', downloadPdf: 'پی ڈی ایف ڈاؤنلوڈ',
    overallScore: 'مجموعی نمبر', student: 'طالب علم', date: 'تاریخ',
    topic: 'منطق کا تعارف', playTime: 'کھیلنے کا وقت',
    slide: 'سلائیڈ', of: 'میں سے', question: 'سوال', score: 'نمبر',
    streak: 'سلسلہ', lives: 'جانیں', bankQuit: 'پوائنٹس محفوظ کرو اور نکلو',
    challengeComplete: '!چیلنج مکمل', gameOver: '!کھیل ختم',
    runesCollected: 'منطق کے نشان', zordsCaught: 'پکڑے گئے زورڈز',
    sailToIsland: '!جزیرے پر جاؤ', sailToBeach: 'ساحل پر جاؤ',
    sailingToIsland: '...پراسرار جزیرے کی طرف', sailingToBeach: '...ساحل کی طرف واپسی',
    perfectCast: '!بہترین پھینک', goodCast: '!اچھی پھینک',
    waitingBite: '...کاٹنے کا انتظار', fishOn: '!مچھلی آئی',
    easyReel: '!بہترین پھینک - آسان', mashSpace: '!اسپیس دبائیں',
    nothingHere: 'یہاں کچھ نہیں ملا', alreadyCollected: 'آپ یہ نشان پہلے لے چکے ہیں',
    wrongAnswer: '!غلط', correctAnswer: '!صحیح', theAnswerIs: ':صحیح جواب ہے',
    comeBackLater: '!واپس آ کر دوبارہ کوشش کرو', catchSuccessful: '!کامیاب پکڑ',
    brokeFree: '!آزاد ہو گیا', escaped: '!فرار', defeated: '!شکست',
    victory: '!فتح', youWereDefeated: '...آپ ہار گئے',
    caught: '!پکڑا گیا', giveNickname: ':اسے ایک نام دو',
    chooseZord: '!ایک زورڈ چنو',
    yourZordFainted: '!آپ کا زورڈ بے ہوش ہو گیا! دوسرا چنو',
    allZordsFainted: '!سب زورڈز بے ہوش ہو گئے',
    cantRunArena: '!میدان کی لڑائی سے بھاگ نہیں سکتے',
    noZords: '!ابھی آپ کے پاس کوئی زورڈ نہیں', startChallenge: '!چیلنج شروع کرو',
    tellMeMore: 'مزید بتاؤ', notNow: 'ابھی نہیں',
    returnToTown: 'گاؤں واپس جاؤ', returnToArena: 'میدان واپس جاؤ',
    startTraining: 'تربیت شروع کرو', backToSpa: 'سپا واپس جاؤ',
    trainingComplete: '!تربیت مکمل', addToBench: 'ٹیم میں شامل کرو',
    removeFromBench: 'ہٹاؤ', benchFull: 'ٹیم بھری ہوئی',
    challenge: 'چیلنج', rematch: 'دوبارہ مقابلہ',
    theLegendOf: 'کی  داستان',
    worldsOfKnowledge: 'علم کی دنیائیں',
    emptySlotN: 'خالی جگہ',
    selectLanguage: 'زبان',
    built: 'بنایا گیا', build: 'بناؤ', theArena: 'میدان',
    continueBattle: 'لڑائی جاری رکھو', yourZords: 'تمہارے زورڈز', goodbye: 'الوداع',
    trainZords: 'اپنے زورڈز کو تربیت دو (سوالوں کے جواب دے کر XP کماؤ!)',
    trainDesc: 'تمام بینچ زورڈز کے لیے XP کمانے کے لیے 5 سوالوں کے صحیح جواب دو۔ فی سیشن 5 یاقوت لاگت ہے۔',
    remove: 'ہٹاؤ', collect: 'جمع کرو!',
    runeYours: '!صحیح! نشان تمہارا ہے',
    readyChallenge: 'منطقی مہارتیں آزمانے کے لیے تیار ہو؟ چیلنج موڈ میں داخل ہو!',
    spaComplete: 'زورڈ سپا - تربیت مکمل!',
    notQuiteRight: 'بالکل درست نہیں۔',
    gotIt: 'سمجھ گئے! آگے بڑھتے ہیں۔',
    studyAnswer: 'جواب پڑھو، پھر دوبارہ کوشش کرو تاکہ پکڑنے کا دوسرا موقع ملے!',
    classify: ':اس بیان کو درجہ بندی کرو', spotFallacy: ':اس دلیل میں غلطی ڈھونڈو',
    checkAnswers: 'جوابات جانچو', matchFrom: ':سے ملاؤ', matchTo: ':کے ساتھ ملاؤ',
    clickToBuild: '...نیچے عناصر پر کلک کرو تاکہ بناؤ',
    undo: 'واپس لو', clear: 'صاف کرو', submit: 'جمع کراؤ', testCircuit: 'سرکٹ جانچو',
    fightYourself: 'خود سے لڑو', runAway: 'بھاگو',
    allHealedUp: '!لو! سب ٹھیک ہو گئے',
    tellAboutZords: 'زورڈز کے بارے میں بتاؤ',
    tellAboutIsland: 'جزیرے کے بارے میں بتاؤ',
    aimCast: '!تیر/WASD سے نشانہ لگاؤ، پھینکنے کے لیے اسپیس دباؤ',
    noBite: 'کوئی کاٹ نہیں... لہر سے بہت دور۔ دوبارہ کوشش کے لیے اسپیس دباؤ۔',
    nibbling: '...کوئی چیز کترا رہی ہے',
    fishBrokeFree: '!آخری لمحے میں مچھلی آزاد ہو گئی! دوبارہ کوشش کے لیے اسپیس دباؤ',
    fishGotAway: '!مچھلی بھاگ گئی! دوبارہ کوشش کے لیے اسپیس دباؤ',
    keepFishing: 'مچھلی پکڑتے رہو', leave: 'چلے جاؤ',
    casting: '...پھینک رہے ہیں', reeledIn: '!واپس کھینچا۔ دوبارہ نشانہ لو اور پھینکو',
    interactEnterHouse: '[E/اسپیس] گھر میں جاؤ',
    interactEnterStore: '[E/اسپیس] دکان میں جاؤ',
    interactReadSign: '[E/اسپیس] تختی پڑھو',
    interactEnter: '[E/اسپیس] داخل ہو',
    interactFish: '[E/اسپیس] یہاں مچھلی پکڑو',
    interactArena: '[E/اسپیس] میدان میں جاؤ',
    interactHospital: '[E/اسپیس] زورڈ ہسپتال',
    interactSpa: '[E/اسپیس] زورڈ سپا',
    interactTalk: '[E/اسپیس] بات کرو',
    interactBuild: '[E/اسپیس] تعمیری مینو کھولو',
    hpFull: 'HP بھرا ہوا ہے', noItems: 'کوئی چیز نہیں',
    equipment: 'سازوسامان', buildingMaterials: 'تعمیری سامان',
    why: 'کیوں؟',
    loc_cave: 'غاریں', loc_town: 'سرسبز گاؤں', loc_forest: 'سرگوشی کا جنگل',
    loc_beach: 'مرجانی خلیج', loc_mountains: 'لوہے کی چوٹی', loc_zordarena: 'زورڈ کولیزیم',
    loc_island: 'پراسرار جزیرہ', loc_peak_1: 'پتھریلی پہاڑیاں', loc_peak_2: 'صنوبر کی چوٹی',
    loc_peak_3: 'منجمد گھاٹی', loc_peak_4: 'ہوا سے بہتی چٹان', loc_peak_5: 'چوٹی',
    loc_temple_1: 'سچائی کا ہال', loc_temple_2: 'انکار کا کمرہ',
    loc_temple_3: 'عظیم کتب خانہ', loc_temple_4: 'منجمد حرم',
    loc_temple_5: 'لاوے کی بھول بھلیاں', loc_temple_6: 'درمیان کی خلا',
    loc_temple_7: 'سب سے بڑے منطق دان کا حرم',
    sign_cave: '<-- سرسبز گاؤں کا راستہ -->',
    sign_town_left: '<-- غاریں (دشمن!)',
    sign_town_right: 'سرگوشی کا جنگل -->',
    sign_town_north: 'مرجانی خلیج ^',
    sign_town_south: 'v لوہے کی چوٹی',
    sign_forest_left: '<-- گاؤں واپس',
    sign_forest_right: 'منطق کا مندر --> (پہلے منطق کے آقا کو ہراؤ!)',
    sign_beach_south: 'گاؤں واپس v',
    sign_beach_dock: 'ماہی گیری کا گھاٹ - اپنی لکیر پھینکو!',
    sign_mtn_north: 'گاؤں واپس ^',
    sign_mtn_deep: 'خبردار! طاقتور مخلوقات چوٹیوں میں گہرائی میں رہتی ہیں۔',
    sign_mtn_south: 'v چوٹی کی چڑھائی (5 منزلیں چوٹی تک!)',
    sign_peak: 'ہوا پتلی ہوتی جا رہی ہے... چڑھتے رہو!',
    sign_beach_ferry: 'پراسرار جزیرے کی طرف کشتی! کیپٹن فن سے بات کرو۔',
    sign_island_ferry: 'مرجانی خلیج واپس کشتی۔ کیپٹن فن سے بات کرو۔',
    sign_island: 'پراسرار جزیرے میں خوش آمدید! نایاب زورڈز یہاں گھومتے ہیں۔',
    sign_town_arena: 'زورڈ کولیزیم v (لڑو، شفا پاؤ اور تربیت کرو!)',
    sign_arena_battle: 'میدان - گاؤں کے تربیت کاروں سے لڑو!',
    sign_arena_hospital: 'زورڈ ہسپتال - اپنے زورڈز کو شفا دو!',
    sign_arena_spa: 'زورڈ سپا - تربیت کرو اور سطح بڑھاؤ!',
    sign_arena_exit: 'گاؤں واپس v',
    sign_island_store: 'Frugalway - جزیرے کی گروسری دکان'
});
