// Spanish translations for ZordPath
registerLanguage('es', 'Espanol', {
    pushStart: 'NUEVO JUEGO', continue: 'Continuar', correct: 'Correcto!', incorrect: 'Incorrecto!',
    tryAgain: 'Intentar de Nuevo', next: 'Siguiente', back: 'Atras', viewDiagram: 'Ver Diagrama',
    startQuiz: 'Comenzar Quiz!', fight: 'LUCHAR', zord: 'ZORD', item: 'OBJETO', run: 'HUIR',
    attack: 'Atacar', switchZord: 'Cambiar Zord', retreat: 'Retirada', potion: 'Pocion',
    deploy: 'Desplegar', catch: 'Capturar', block: 'Bloquear', action: 'ACCION', talk: 'HABLAR',
    inventory: 'INV', map: 'MAPA', help: 'AYUDA', quiz: 'QUIZ',
    leaveStore: 'Salir de Tienda', buy: 'Comprar', soldOut: 'AGOTADO', rubies: 'Rubies',
    healAll: 'Curar Todos los Zords', free: 'GRATIS', confirm: 'Confirmar', cancel: 'Cancelar',
    close: 'Cerrar', save: 'Guardar', delete: 'Borrar', emptySlot: 'Espacio Vacio',
    enterHouse: 'Entrar a Casa', enterStore: 'Entrar a Tienda', enterArena: 'Entrar a Arena',
    readSign: 'Leer Letrero', fishHere: 'Pescar aqui', enter: 'Entrar', search: 'Buscar',
    exit: 'Salir', zordHospital: 'Hospital Zord', zordSpa: 'Spa Zord',
    testing: 'PRUEBAS', levelUp: 'SUBISTE DE NIVEL!', reportCard: 'BOLETA DE CALIFICACIONES',
    strengths: 'Fortalezas', needsPractice: 'Necesita Practica',
    mostMissed: 'Preguntas Mas Falladas', downloadPdf: 'Descargar PDF',
    overallScore: 'Puntaje General', student: 'Estudiante', date: 'Fecha',
    topic: 'Introduccion a la Logica', playTime: 'Tiempo de Juego',
    slide: 'Diapositiva', of: 'de', question: 'Pregunta', score: 'Puntaje',
    streak: 'Racha', lives: 'Vidas', bankQuit: 'Guardar Puntos y Salir',
    challengeComplete: 'Desafio Completado!', gameOver: 'Fin del Juego!',
    runesCollected: 'Runas de Logica', zordsCaught: 'Zords Capturados',
    sailToIsland: 'Navegar a la Isla!', sailToBeach: 'Navegar a la Playa',
    sailingToIsland: 'Navegando a la Isla Misteriosa...', sailingToBeach: 'Regresando a Coral Cove...',
    perfectCast: 'Lanzamiento perfecto!', goodCast: 'Buen lanzamiento!',
    waitingBite: 'Esperando una mordida...', fishOn: 'PICO!',
    easyReel: 'Lanzamiento perfecto - facil de pescar!', mashSpace: 'Presiona Espacio para pescar!',
    nothingHere: 'No hay nada que encontrar aqui.', alreadyCollected: 'Ya recolectaste esta runa.',
    wrongAnswer: 'Incorrecto!', correctAnswer: 'Correcto!', theAnswerIs: 'La respuesta es:',
    comeBackLater: 'Vuelve e intentalo de nuevo!', catchSuccessful: 'Captura exitosa!',
    brokeFree: 'se libero!', escaped: 'Escapaste!', defeated: 'derrotado!',
    victory: 'Victoria!', youWereDefeated: 'Fuiste derrotado...',
    caught: 'CAPTURADO!', giveNickname: 'Dale un apodo:',
    chooseZord: 'Elige un Zord para desplegar!',
    yourZordFainted: 'Tu Zord se desmayo! Elige otro!',
    allZordsFainted: 'Todos tus Zords se desmayaron!',
    cantRunArena: 'No puedes huir de una batalla de Arena!',
    noZords: 'Aun no tienes Zords!', startChallenge: 'Comenzar Desafio!',
    tellMeMore: 'Cuentame mas', notNow: 'Ahora no',
    returnToTown: 'Volver al Pueblo', returnToArena: 'Volver a la Arena',
    startTraining: 'Comenzar Entrenamiento', backToSpa: 'Volver al Spa',
    trainingComplete: 'Entrenamiento Completado!', addToBench: 'Agregar al Equipo',
    removeFromBench: 'Quitar', benchFull: 'Equipo Lleno',
    challenge: 'Desafiar', rematch: 'Revancha',
    selectLanguage: 'Idioma'
});
