// Urdu translations for ZordPath
registerLanguage('ur', 'اردو', '\u{1F1F5}\u{1F1F0}', {
    pushStart: 'نیا کھیل', continue: 'جاری رکھیں', correct: '!صحیح', incorrect: '!غلط',
    tryAgain: 'دوبارہ کوشش کریں', next: 'اگلا', back: 'واپس', viewDiagram: 'خاکہ دیکھیں',
    startQuiz: '!کوئز شروع کریں', fight: 'لڑو', zord: 'زورڈ', item: 'چیز', run: 'بھاگو',
    attack: 'حملہ', switchZord: 'زورڈ بدلو', retreat: 'پیچھے ہٹو', potion: 'دوائی',
    deploy: 'تعینات', catch: 'پکڑو', block: 'روکو', action: 'عمل', talk: 'بات',
    inventory: 'سامان', map: 'نقشہ', help: 'مدد', quiz: 'کوئز',
    leaveStore: 'دکان چھوڑو', buy: 'خریدو', soldOut: 'ختم', rubies: 'یاقوت',
    healAll: 'سب زورڈز کو شفا دو', free: 'مفت', confirm: 'تصدیق', cancel: 'منسوخ',
    close: 'بند', save: 'محفوظ', delete: 'حذف', emptySlot: 'خالی جگہ',
    enterHouse: 'گھر میں جاؤ', enterStore: 'دکان میں جاؤ', enterArena: 'میدان میں جاؤ',
    readSign: 'تختی پڑھو', fishHere: 'یہاں مچھلی پکڑو', enter: 'داخل ہو', search: 'تلاش',
    exit: 'باہر نکلو', zordHospital: 'زورڈ ہسپتال', zordSpa: 'زورڈ سپا',
    testing: 'ٹیسٹنگ', levelUp: '!سطح بڑھ گئی', reportCard: 'رپورٹ کارڈ',
    strengths: 'طاقتیں', needsPractice: 'مشق کی ضرورت',
    mostMissed: 'سب سے زیادہ غلط سوالات', downloadPdf: 'پی ڈی ایف ڈاؤنلوڈ',
    overallScore: 'مجموعی نمبر', student: 'طالب علم', date: 'تاریخ',
    topic: 'منطق کا تعارف', playTime: 'کھیلنے کا وقت',
    slide: 'سلائیڈ', of: 'میں سے', question: 'سوال', score: 'نمبر',
    streak: 'سلسلہ', lives: 'جانیں', bankQuit: 'پوائنٹس محفوظ کرو اور نکلو',
    challengeComplete: '!چیلنج مکمل', gameOver: '!کھیل ختم',
    runesCollected: 'منطق کے نشان', zordsCaught: 'پکڑے گئے زورڈز',
    sailToIsland: '!جزیرے پر جاؤ', sailToBeach: 'ساحل پر جاؤ',
    sailingToIsland: '...پراسرار جزیرے کی طرف', sailingToBeach: '...ساحل کی طرف واپسی',
    perfectCast: '!بہترین پھینک', goodCast: '!اچھی پھینک',
    waitingBite: '...کاٹنے کا انتظار', fishOn: '!مچھلی آئی',
    easyReel: '!بہترین پھینک - آسان', mashSpace: '!اسپیس دبائیں',
    nothingHere: 'یہاں کچھ نہیں ملا', alreadyCollected: 'آپ یہ نشان پہلے لے چکے ہیں',
    wrongAnswer: '!غلط', correctAnswer: '!صحیح', theAnswerIs: ':صحیح جواب ہے',
    comeBackLater: '!واپس آ کر دوبارہ کوشش کرو', catchSuccessful: '!کامیاب پکڑ',
    brokeFree: '!آزاد ہو گیا', escaped: '!فرار', defeated: '!شکست',
    victory: '!فتح', youWereDefeated: '...آپ ہار گئے',
    caught: '!پکڑا گیا', giveNickname: ':اسے ایک نام دو',
    chooseZord: '!ایک زورڈ چنو',
    yourZordFainted: '!آپ کا زورڈ بے ہوش ہو گیا! دوسرا چنو',
    allZordsFainted: '!سب زورڈز بے ہوش ہو گئے',
    cantRunArena: '!میدان کی لڑائی سے بھاگ نہیں سکتے',
    noZords: '!ابھی آپ کے پاس کوئی زورڈ نہیں', startChallenge: '!چیلنج شروع کرو',
    tellMeMore: 'مزید بتاؤ', notNow: 'ابھی نہیں',
    returnToTown: 'گاؤں واپس جاؤ', returnToArena: 'میدان واپس جاؤ',
    startTraining: 'تربیت شروع کرو', backToSpa: 'سپا واپس جاؤ',
    trainingComplete: '!تربیت مکمل', addToBench: 'ٹیم میں شامل کرو',
    removeFromBench: 'ہٹاؤ', benchFull: 'ٹیم بھری ہوئی',
    challenge: 'چیلنج', rematch: 'دوبارہ مقابلہ',
    theLegendOf: 'کی  داستان',
    worldsOfKnowledge: 'علم کی دنیائیں',
    emptySlotN: 'خالی جگہ',
    selectLanguage: 'زبان'
});
