// Japanese translations for ZordPath
registerLanguage('ja', '日本語', '\u{1F1EF}\u{1F1F5}', {
    pushStart: 'ニューゲーム', continue: 'つづける', correct: '正解！', incorrect: '不正解！',
    tryAgain: 'もう一度', next: '次へ', back: '戻る', viewDiagram: '図を見る',
    startQuiz: 'クイズ開始！', fight: 'たたかう', zord: 'ゾード', item: 'アイテム', run: 'にげる',
    attack: 'こうげき', switchZord: 'ゾード交代', retreat: '撤退', potion: 'ポーション',
    deploy: '出動', catch: 'つかまえる', block: 'ぼうぎょ', action: 'アクション', talk: 'はなす',
    inventory: '持ち物', map: '地図', help: 'ヘルプ', quiz: 'クイズ',
    leaveStore: '店を出る', buy: '買う', soldOut: '売り切れ', rubies: 'ルビー',
    healAll: '全ゾードを回復', free: '無料', confirm: '決定', cancel: 'キャンセル',
    close: '閉じる', save: 'セーブ', delete: '削除', emptySlot: '空きスロット',
    enterHouse: '家に入る', enterStore: '店に入る', enterArena: 'アリーナに入る',
    readSign: '看板を読む', fishHere: 'ここで釣る', enter: '入る', search: 'さがす',
    exit: '出る', zordHospital: 'ゾード病院', zordSpa: 'ゾードスパ',
    testing: 'テスト中', levelUp: 'レベルアップ！', reportCard: '成績表',
    strengths: '得意分野', needsPractice: '練習が必要',
    mostMissed: '最も間違えた問題', downloadPdf: 'PDFダウンロード',
    overallScore: '総合スコア', student: '生徒', date: '日付',
    topic: '論理学入門', playTime: 'プレイ時間',
    slide: 'スライド', of: '/', question: '問題', score: 'スコア',
    streak: '連続', lives: 'ライフ', bankQuit: 'ポイントを保存して終了',
    challengeComplete: 'チャレンジ達成！', gameOver: 'ゲームオーバー！',
    runesCollected: '論理ルーン', zordsCaught: '捕獲したゾード',
    sailToIsland: '島へ出航！', sailToBeach: 'ビーチへ戻る',
    sailingToIsland: '不思議な島へ航海中...', sailingToBeach: 'コーラルコーブへ帰還中...',
    perfectCast: 'パーフェクト！', goodCast: 'グッドキャスト！',
    waitingBite: 'アタリを待っています...', fishOn: 'ヒット！',
    easyReel: 'パーフェクト - 楽々！', mashSpace: 'スペースキーを連打！',
    nothingHere: '何も見つかりません。', alreadyCollected: 'このルーンは既に集めました。',
    wrongAnswer: '不正解！', correctAnswer: '正解！', theAnswerIs: '答えは：',
    comeBackLater: 'また来て挑戦しよう！', catchSuccessful: '捕獲成功！',
    brokeFree: '逃げられた！', escaped: '脱出した！', defeated: '倒した！',
    victory: '勝利！', youWereDefeated: '負けてしまった...',
    caught: '捕獲！', giveNickname: 'ニックネームをつけよう：',
    chooseZord: 'ゾードを選んで出動！',
    yourZordFainted: 'ゾードが倒れた！別のを選んで！',
    allZordsFainted: '全ゾードが倒れた！',
    cantRunArena: 'アリーナでは逃げられない！',
    noZords: 'まだゾードがいません！', startChallenge: 'チャレンジ開始！',
    tellMeMore: 'もっと教えて', notNow: '今はいい',
    returnToTown: '町に戻る', returnToArena: 'アリーナに戻る',
    startTraining: 'トレーニング開始', backToSpa: 'スパに戻る',
    trainingComplete: 'トレーニング完了！', addToBench: 'チームに加える',
    removeFromBench: '外す', benchFull: 'チーム満員',
    challenge: 'チャレンジ', rematch: '再戦',
    theLegendOf: '伝説の',
    worldsOfKnowledge: '知識の世界',
    emptySlotN: '空きスロット',
    selectLanguage: '言語',
    built: '建設済み', build: '建てる', theArena: 'アリーナ',
    continueBattle: '戦闘を続ける', yourZords: 'あなたのゾード', goodbye: 'さようなら',
    trainZords: 'ゾードを鍛えよう（問題に答えてXPをゲット！）',
    trainDesc: '5問正解してベンチのゾード全員にXPを獲得しよう。1回3セッションあたりルビー5個が必要。',
    remove: '外す', collect: 'ゲット！',
    runeYours: '正解！ルーンはゲットだ！',
    readyChallenge: 'ロジックスキルを試す準備はいい？チャレンジモードに入ろう！',
    spaComplete: 'ゾードスパ - トレーニング完了！',
    notQuiteRight: 'ちょっと違う。',
    gotIt: 'わかった！次に進もう。',
    studyAnswer: '答えをよく見て、もう一度挑戦して捕獲のチャンスをつかもう！',
    classify: 'この文を分類しよう：', spotFallacy: 'この論点の誤りを見つけよう：',
    checkAnswers: '答えを確認', matchFrom: 'ここからマッチ：', matchTo: 'ここへマッチ：',
    clickToBuild: '下の要素をクリックして作ろう...',
    undo: '元に戻す', clear: 'クリア', submit: '提出', testCircuit: '回路をテスト',
    fightYourself: '自分と戦う', runAway: '逃げる',
    allHealedUp: 'よし！全員回復した！',
    tellAboutZords: 'ゾードについて教えて',
    tellAboutIsland: '島について教えて',
    aimCast: '矢印キー/WASDで狙いを定め、スペースで投げよう！',
    noBite: 'アタリなし...波紋から遠すぎる。スペースキーで再挑戦。',
    nibbling: '何かがかじっている...',
    fishBrokeFree: '最後の瞬間に魚が逃げた！スペースキーで再挑戦。',
    fishGotAway: '魚に逃げられた！スペースキーで再挑戦。',
    keepFishing: '釣り続ける', leave: '立ち去る',
    casting: '投げ中...', reeledIn: '巻き取った。また狙いを定めて投げよう！',
    interactEnterHouse: '【E/スペース】家に入る',
    interactEnterStore: '【E/スペース】店に入る',
    interactReadSign: '【E/スペース】看板を読む',
    interactEnter: '【E/スペース】入る',
    interactFish: '【E/スペース】ここで釣る',
    interactArena: '【E/スペース】アリーナに入る',
    interactHospital: '【E/スペース】ゾード病院',
    interactSpa: '【E/スペース】ゾードスパ',
    interactTalk: '【E/スペース】はなす',
    interactBuild: '【E/スペース】建設メニューを開く',
    hpFull: 'HPが満タン', noItems: 'アイテムなし',
    equipment: '装備', buildingMaterials: '建設素材',
    why: 'なぜ？',
    loc_cave: '洞窟群', loc_town: '緑豊かな村', loc_forest: 'ささやきの森',
    loc_beach: 'サンゴ入り江', loc_mountains: '鉄峰山脈', loc_zordarena: 'ゾードコロシアム',
    loc_island: '謎の島', loc_peak_1: '岩山の麓', loc_peak_2: '松の尾根',
    loc_peak_3: '凍てつく峠', loc_peak_4: '風の岩場', loc_peak_5: '山頂',
    loc_temple_1: '真実の間', loc_temple_2: '否定の部屋',
    loc_temple_3: '大図書館', loc_temple_4: '凍てつく聖域',
    loc_temple_5: '溶岩の迷宮', loc_temple_6: '虚空の狭間',
    loc_temple_7: '大論理師の聖域',
    sign_cave: '緑豊かな村への出口 -->',
    sign_town_left: '<-- 洞窟群（敵がいる！）',
    sign_town_right: 'ささやきの森 -->',
    sign_town_north: 'サンゴ入り江 ^',
    sign_town_south: 'v 鉄峰山脈',
    sign_forest_left: '<-- 村に戻る',
    sign_forest_right: '論理の神殿 -->（まず論理王を倒そう！）',
    sign_beach_south: '村に戻る v',
    sign_beach_dock: '釣り桟橋 - 糸を投げよう！',
    sign_mtn_north: '村に戻る ^',
    sign_mtn_deep: '注意！山の奥深くには強力な生き物がいる。',
    sign_mtn_south: 'v 山頂への道（頂上まで5ステージ！）',
    sign_peak: '空気が薄くなってきた...登り続けよう！',
    sign_beach_ferry: '謎の島へのフェリー！フィン船長に話しかけよう。',
    sign_island_ferry: 'サンゴ入り江へ戻るフェリー。フィン船長に話しかけよう。',
    sign_island: '謎の島へようこそ！珍しいゾードがいるよ。',
    sign_town_arena: 'ゾードコロシアム v（バトル、回復、トレーニング！）',
    sign_arena_battle: 'アリーナ - 村のトレーナーとバトル！',
    sign_arena_hospital: 'ゾード病院 - ゾードを回復しよう！',
    sign_arena_spa: 'ゾードスパ - トレーニングしてレベルアップ！',
    sign_arena_exit: '村に戻る v',
    sign_island_store: 'Frugalway - 島の食料品店'
});

// NPC Dialogue translations
LANGUAGES.ja.npcDialogue = {
    'Elder Tautology': [
        'ようこそ、ロジックランドへ！ここでは真実と理性が最大の武器だよ。',
        '覚えておいて：文は「真」か「偽」のどちらかだ。古典論理に中間はない！',
        '論理王を倒したいなら、5つのレッスンをすべてマスターしなくちゃ。しっかり勉強してね！'
    ],
    'Merchant Mira': [
        '何か買いたい？お店に行ってみて！',
        'パラドックスコウモリはクイズに勝てばルビーをたくさん落とすって聞いたよ。',
        'ロジックランドで家を建てたい？お店で木材、石、釘が必要だよ。'
    ],
    'Scout Axiom': [
        '近くの洞窟を探索してたんだ。どこの隅にも敵が潜んでるよ！',
        '戦闘の前には論理のレッスンを学んで、問題に答えないといけないよ。',
        '敵が強いほど、もらえるルビーが多い。でもクイズも難しくなるよ！'
    ],
    'Al-Muṣawwir': [
        'あ、仲間の建築家だ！材料が集まったら、建設について話しに来てよ。',
        '小さなキャビンには木材5本と石3個が必要だよ。工房はもっと必要！',
        'ルビーもいいけど、文明を作るのは材料だよ！'
    ],
    'ZordTamer Kira': [
        'ようこそ、若き使いこなし師！ゾードはこの地を歩き回る生き物だよ。ゾードケージがあれば手なずけられるよ！',
        '戦闘でゾードを弱らせてから、Cを押してゾードケージを投げよう。弱いほど捕まえやすいよ！',
        'ゾードケージを売ったりゾードを回復したりできるよ。Zを押せばいつでもゾードリストが見られる！',
        '超レアなゾードもいるよ。神殿のプリズマティックドレイクはほぼ捕まえられないって言われてるよ！',
        '全部集めて、ロジックランド最強のゾード使いになろう！'
    ],
    'Challenge Master Rho': [
        'ぼくはチャレンジマスター！論理がわかると思うなら、証明してみて！',
        'チャレンジモードでは問題が次々と出てくるよ。連続正解でマルチプライヤーを上げよう！',
        'でも気をつけて——3回間違えたらゲームオーバー。やめるときはポイントをルビーにして保存しよう！',
        '長く続けるほど、もらえるバッジが良くなるよ。LEGENDARYバッジを手に入れられる？'
    ],
    'Captain Coral': [
        'アホイ！コーラルコーブビーチへようこそ！潮風が頭を爽やかにして、論理的思考を助けてくれるよ。',
        'タイドクラブには気をつけて——挟む力が強い！シェルゴーレムも藤壺みたいに硬いよ。',
        'あそこの桟橋は釣りにぴったりだよ。村の池より大きな魚が海にはいるよ！',
        'ジェリーフィッシュドリフトが見えたら、ショックスティングに気をつけて。電気攻撃はすごく痛い！'
    ],
    'Ranger Flint': [
        'アイアンピーク山脈へようこそ！空気は薄いけど、景色は最高だよ。',
        'クリスタルイエティはこの山々で最も強い生き物だよ。捕まえた人はほとんどいない！',
        'フロストウルフは雪原で狩りをしてるよ。速くて、氷攻撃が痛い。',
        '奥に小さな高山湖があるよ——釣り竿があれば釣りができるよ。'
    ],
    'Ferry Captain Finn': [
        'アホイ！海の向こうの謎の島へフェリーで運ぶよ！',
        '島には本土では見つからない生き物がいるよ。',
        '島の周りの深海にストームマンタが潜んでるって言われてるよ。超レアだよ！',
        '島の人たちはフレンドリーだよ。独自のお店と釣りスポットがあるよ。'
    ],
    'Island Elder Kai': [
        'この島へようこそ、旅人！本土からここまで来る人はほとんどいないよ。',
        'ここの生き物はユニークだよ——ヤシガニ、リーフサーペント、そして伝説のストームマンタ。',
        'ティキスピリットたちが古代の知識を守っているよ。倒して最深の論理を学ぼう！',
        'ビーチに戻りたければ、フェリー桟橋は北にあるよ。'
    ]
};

// Store item translations
LANGUAGES.ja.storeItems = {
    'Health Potion':   { name: '回復ポーション',       desc: 'HP30回復' },
    'Wooden Shield':   { name: '木の盾',               desc: '+3防御、戦闘中にガード（Shift）' },
    'Iron Sword':      { name: '鉄の剣',               desc: '+5攻撃、素早い斬撃' },
    'Magic Staff':     { name: '魔法の杖',             desc: '戦闘中に火の玉を放て！' },
    'Fishing Pole':    { name: '釣り竿',               desc: '湖で釣りをしよう！魚を食べるか売ろう。' },
    'Wood Planks':     { name: '木の板',               desc: '基本的な建設素材' },
    'Stone Blocks':    { name: '石ブロック',           desc: '丈夫な建設素材' },
    'Iron Nails':      { name: '鉄の釘',               desc: 'すべてをつなぎ止める' },
    'Glass Panes':     { name: 'ガラス板',             desc: '窓に使う' },
    'Rope':            { name: 'ロープ',               desc: '建設に役立つ' },
    'Island Bar':      { name: 'アイランドバー',       desc: '甘いおやつ、HP25回復' },
    'Coconut Water':   { name: 'ココナッツウォーター', desc: 'リフレッシュ！HP15回復' },
    'Tropic Charm':    { name: 'トロピックチャーム',   desc: '島のゾードの捕獲率+10%' },
    'Palm Wood':       { name: 'ヤシの木材',           desc: '軽い島の木材' }
};
