// French translations for ZordPath
registerLanguage('fr', 'Francais', {
    pushStart: 'NOUVELLE PARTIE', continue: 'Continuer', correct: 'Correct !', incorrect: 'Incorrect !',
    tryAgain: 'Reessayer', next: 'Suivant', back: 'Retour', viewDiagram: 'Voir le Diagramme',
    startQuiz: 'Commencer le Quiz !', fight: 'COMBAT', zord: 'ZORD', item: 'OBJET', run: 'FUIR',
    attack: 'Attaquer', switchZord: 'Changer de Zord', retreat: 'Retraite', potion: 'Potion',
    deploy: 'Deployer', catch: 'Capturer', block: 'Bloquer', action: 'ACTION', talk: 'PARLER',
    inventory: 'INV', map: 'CARTE', help: 'AIDE', quiz: 'QUIZ',
    leaveStore: 'Quitter le Magasin', buy: 'Acheter', soldOut: 'EPUISE', rubies: 'Rubis',
    healAll: 'Soigner tous les Zords', free: 'GRATUIT', confirm: 'Confirmer', cancel: 'Annuler',
    close: 'Fermer', save: 'Sauvegarder', delete: 'Supprimer', emptySlot: 'Emplacement Vide',
    enterHouse: 'Entrer dans la Maison', enterStore: 'Entrer dans le Magasin', enterArena: 'Entrer dans l\'Arene',
    readSign: 'Lire le Panneau', fishHere: 'Pecher ici', enter: 'Entrer', search: 'Chercher',
    exit: 'Sortir', zordHospital: 'Hopital Zord', zordSpa: 'Spa Zord',
    testing: 'TEST', levelUp: 'NIVEAU SUPERIEUR !', reportCard: 'BULLETIN SCOLAIRE',
    strengths: 'Points Forts', needsPractice: 'A Travailler',
    mostMissed: 'Questions les Plus Ratees', downloadPdf: 'Telecharger PDF',
    overallScore: 'Score Global', student: 'Eleve', date: 'Date',
    topic: 'Introduction a la Logique', playTime: 'Temps de Jeu',
    slide: 'Diapositive', of: 'sur', question: 'Question', score: 'Score',
    streak: 'Serie', lives: 'Vies', bankQuit: 'Encaisser et Quitter',
    challengeComplete: 'Defi Termine !', gameOver: 'Fin de Partie !',
    runesCollected: 'Runes de Logique', zordsCaught: 'Zords Captures',
    sailToIsland: 'Naviguer vers l\'Ile !', sailToBeach: 'Retour a la Plage',
    sailingToIsland: 'Navigation vers l\'Ile Mysterieuse...', sailingToBeach: 'Retour a Coral Cove...',
    perfectCast: 'Lancer parfait !', goodCast: 'Bon lancer !',
    waitingBite: 'En attente d\'une touche...', fishOn: 'CA MORD !',
    easyReel: 'Lancer parfait - facile !', mashSpace: 'Appuyez sur Espace pour mouliner !',
    nothingHere: 'Rien a trouver ici.', alreadyCollected: 'Vous avez deja cette rune.',
    wrongAnswer: 'Faux !', correctAnswer: 'Correct !', theAnswerIs: 'La reponse est :',
    comeBackLater: 'Revenez et reessayez !', catchSuccessful: 'Capture reussie !',
    brokeFree: 's\'est libere !', escaped: 'Echappe !', defeated: 'vaincu !',
    victory: 'Victoire !', youWereDefeated: 'Vous avez ete vaincu...',
    caught: 'CAPTURE !', giveNickname: 'Donnez-lui un surnom :',
    chooseZord: 'Choisissez un Zord a deployer !',
    yourZordFainted: 'Votre Zord est KO ! Choisissez-en un autre !',
    allZordsFainted: 'Tous vos Zords sont KO !',
    cantRunArena: 'Impossible de fuir un combat d\'Arene !',
    noZords: 'Vous n\'avez pas encore de Zords !', startChallenge: 'Commencer le Defi !',
    tellMeMore: 'Dis-moi en plus', notNow: 'Pas maintenant',
    returnToTown: 'Retour au Village', returnToArena: 'Retour a l\'Arene',
    startTraining: 'Commencer l\'Entrainement', backToSpa: 'Retour au Spa',
    trainingComplete: 'Entrainement Termine !', addToBench: 'Ajouter a l\'Equipe',
    removeFromBench: 'Retirer', benchFull: 'Equipe Pleine',
    challenge: 'Defier', rematch: 'Revanche',
    selectLanguage: 'Langue'
});
