// Traditional Chinese translations for ZordPath
registerLanguage('zh', '中文', {
    pushStart: '新遊戲', continue: '繼續', correct: '正確！', incorrect: '錯誤！',
    tryAgain: '再試一次', next: '下一頁', back: '返回', viewDiagram: '查看圖表',
    startQuiz: '開始測驗！', fight: '戰鬥', zord: '佐德', item: '物品', run: '逃跑',
    attack: '攻擊', switchZord: '更換佐德', retreat: '撤退', potion: '藥水',
    deploy: '部署', catch: '捕捉', block: '防禦', action: '行動', talk: '對話',
    inventory: '背包', map: '地圖', help: '幫助', quiz: '測驗',
    leaveStore: '離開商店', buy: '購買', soldOut: '售罄', rubies: '紅寶石',
    healAll: '治癒所有佐德', free: '免費', confirm: '確認', cancel: '取消',
    close: '關閉', save: '儲存', delete: '刪除', emptySlot: '空位',
    enterHouse: '進入房屋', enterStore: '進入商店', enterArena: '進入競技場',
    readSign: '閱讀告示', fishHere: '在此釣魚', enter: '進入', search: '搜尋',
    exit: '離開', zordHospital: '佐德醫院', zordSpa: '佐德水療',
    testing: '測試中', levelUp: '升級了！', reportCard: '成績單',
    strengths: '強項', needsPractice: '需要練習',
    mostMissed: '最常答錯的問題', downloadPdf: '下載PDF',
    overallScore: '總分', student: '學生', date: '日期',
    topic: '邏輯學入門', playTime: '遊戲時間',
    slide: '頁', of: '/', question: '問題', score: '分數',
    streak: '連勝', lives: '生命', bankQuit: '存分並退出',
    challengeComplete: '挑戰完成！', gameOver: '遊戲結束！',
    runesCollected: '邏輯符文', zordsCaught: '已捕獲佐德',
    sailToIsland: '航向小島！', sailToBeach: '返回海灘',
    sailingToIsland: '航向神秘島嶼...', sailingToBeach: '返回珊瑚灣...',
    perfectCast: '完美拋竿！', goodCast: '不錯的拋竿！',
    waitingBite: '等待魚上鉤...', fishOn: '上鉤了！',
    easyReel: '完美拋竿 - 輕鬆收線！', mashSpace: '快按空白鍵收線！',
    nothingHere: '這裡沒有發現。', alreadyCollected: '你已經收集了這個符文。',
    wrongAnswer: '錯了！', correctAnswer: '正確！', theAnswerIs: '答案是：',
    comeBackLater: '下次再來試試！', catchSuccessful: '捕捉成功！',
    brokeFree: '掙脫了！', escaped: '逃跑了！', defeated: '被擊敗了！',
    victory: '勝利！', youWereDefeated: '你被打敗了...',
    caught: '捕獲！', giveNickname: '給牠取個暱稱：',
    chooseZord: '選擇一隻佐德出戰！',
    yourZordFainted: '你的佐德昏倒了！選另一隻！',
    allZordsFainted: '所有佐德都昏倒了！',
    cantRunArena: '競技場中不能逃跑！',
    noZords: '你還沒有佐德！', startChallenge: '開始挑戰！',
    tellMeMore: '告訴我更多', notNow: '現在不要',
    returnToTown: '返回城鎮', returnToArena: '返回競技場',
    startTraining: '開始訓練', backToSpa: '返回水療',
    trainingComplete: '訓練完成！', addToBench: '加入隊伍',
    removeFromBench: '移除', benchFull: '隊伍已滿',
    challenge: '挑戰', rematch: '重賽',
    selectLanguage: '語言'
});
