// Japanese translations for ZordPath
registerLanguage('ja', '日本語', '\u{1F1EF}\u{1F1F5}', {
    pushStart: 'ニューゲーム', continue: 'つづける', correct: '正解！', incorrect: '不正解！',
    tryAgain: 'もう一度', next: '次へ', back: '戻る', viewDiagram: '図を見る',
    startQuiz: 'クイズ開始！', fight: 'たたかう', zord: 'ゾード', item: 'アイテム', run: 'にげる',
    attack: 'こうげき', switchZord: 'ゾード交代', retreat: '撤退', potion: 'ポーション',
    deploy: '出動', catch: 'つかまえる', block: 'ぼうぎょ', action: 'アクション', talk: 'はなす',
    inventory: '持ち物', map: '地図', help: 'ヘルプ', quiz: 'クイズ',
    leaveStore: '店を出る', buy: '買う', soldOut: '売り切れ', rubies: 'ルビー',
    healAll: '全ゾードを回復', free: '無料', confirm: '決定', cancel: 'キャンセル',
    close: '閉じる', save: 'セーブ', delete: '削除', emptySlot: '空きスロット',
    enterHouse: '家に入る', enterStore: '店に入る', enterArena: 'アリーナに入る',
    readSign: '看板を読む', fishHere: 'ここで釣る', enter: '入る', search: 'さがす',
    exit: '出る', zordHospital: 'ゾード病院', zordSpa: 'ゾードスパ',
    testing: 'テスト中', levelUp: 'レベルアップ！', reportCard: '成績表',
    strengths: '得意分野', needsPractice: '練習が必要',
    mostMissed: '最も間違えた問題', downloadPdf: 'PDFダウンロード',
    overallScore: '総合スコア', student: '生徒', date: '日付',
    topic: '論理学入門', playTime: 'プレイ時間',
    slide: 'スライド', of: '/', question: '問題', score: 'スコア',
    streak: '連続', lives: 'ライフ', bankQuit: 'ポイントを保存して終了',
    challengeComplete: 'チャレンジ達成！', gameOver: 'ゲームオーバー！',
    runesCollected: '論理ルーン', zordsCaught: '捕獲したゾード',
    sailToIsland: '島へ出航！', sailToBeach: 'ビーチへ戻る',
    sailingToIsland: '不思議な島へ航海中...', sailingToBeach: 'コーラルコーブへ帰還中...',
    perfectCast: 'パーフェクト！', goodCast: 'グッドキャスト！',
    waitingBite: 'アタリを待っています...', fishOn: 'ヒット！',
    easyReel: 'パーフェクト - 楽々！', mashSpace: 'スペースキーを連打！',
    nothingHere: '何も見つかりません。', alreadyCollected: 'このルーンは既に集めました。',
    wrongAnswer: '不正解！', correctAnswer: '正解！', theAnswerIs: '答えは：',
    comeBackLater: 'また来て挑戦しよう！', catchSuccessful: '捕獲成功！',
    brokeFree: '逃げられた！', escaped: '脱出した！', defeated: '倒した！',
    victory: '勝利！', youWereDefeated: '負けてしまった...',
    caught: '捕獲！', giveNickname: 'ニックネームをつけよう：',
    chooseZord: 'ゾードを選んで出動！',
    yourZordFainted: 'ゾードが倒れた！別のを選んで！',
    allZordsFainted: '全ゾードが倒れた！',
    cantRunArena: 'アリーナでは逃げられない！',
    noZords: 'まだゾードがいません！', startChallenge: 'チャレンジ開始！',
    tellMeMore: 'もっと教えて', notNow: '今はいい',
    returnToTown: '町に戻る', returnToArena: 'アリーナに戻る',
    startTraining: 'トレーニング開始', backToSpa: 'スパに戻る',
    trainingComplete: 'トレーニング完了！', addToBench: 'チームに加える',
    removeFromBench: '外す', benchFull: 'チーム満員',
    challenge: 'チャレンジ', rematch: '再戦',
    selectLanguage: '言語'
});
